version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202107-01
    environment:
      PHP_VERSION: "8.1"
    steps:
      - checkout
      - run:
          name: Install PHP 8.1
          command: |
            sudo apt-get update
            sudo apt-get install -y software-properties-common
            sudo add-apt-repository ppa:ondrej/php
            sudo apt-get update
            sudo apt-get install -y php8.1 php8.1-cli php8.1-xml php8.1-mbstring php8.1-curl
            curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
            composer install
      - run:
          name: Run tests
          command: vendor/bin/phpunit
