version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4

    steps:
      - checkout

      # Add your build steps here
      - run:
          name: "Install Dependencies"
          command: composer install --prefer-dist --no-progress

      - run:
          name: "Run Tests"
          command: vendor/bin/phpunit

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
